apiVersion: v1
kind: ConfigMap
metadata:
  name: repository-cm
data:
  ENV: "staging"
  # central database pod settings
  DB_HOST: "db"
  DB_NAME: "repository_db"
  DB_PORT: "5432"
  # container mount points
  STORAGE_PATH: "/var/edm/data"  # main document store
  ATNA_LOG_BACKUP_PATH: "/var/edm/atna_backup"  # atna emergency location
  # logging configuration
  DEBUG: "1"
  LOGLEVEL: "DEBUG"
  # api paths used in DRF url patterns
  ITI_41_API_PATH: "api/iti41"
  ITI_41_REST_PATH: "api/int/iti41"
  ITI_43_API_PATH: "api/iti43"
  ITI_43_REST_PATH: "api/int/iti43"
  # internal path to registry for iti41 forwarding
  ITI_42_BRIDGE_PATH: "api/iti42"
  ITI_42_BRIDGE_PORT: "8080"
  ITI_42_BRIDGE_HOST: "registry"
  ITI_42_BRIDGE_REST_PATH: "api/int/iti42"
  # repository identifier
  REPOSITORY_UNIQUE_ID: "pez-repository-01"  # tbc
  # internal path to atna logging service
  ATNA_HOST: "atna"
  ATNA_PORT: "8008"
  ATNA_ENDPOINT: "api/v1/audit_event"
  # container mount point for backup atna logs
  # internal path to ws-security auth service
  AUTH_HOST: "adminer"
  AUTH_PORT: "8009"
  AUTH_ENDPOINT: "/api/v1/cert/verify"
  JWT_VALIDATION_URL: "https://auth.test.pomorskie.cgmpolska.pl/auth/realms/internal/protocol/openid-connect/userinfo"
  # openapi settings
  SWAGGER_UI_PATH: "api/schema/swagger-ui/"
  API_SCHEMA_PATH: "api/schema/"
  # rabbitmq audit logs
  MQ_AUDIT_EXCHANGE: "auditindex"
  MQ_ROUTING_KEY: "audit-log.command.create"
  MQ_USER: "edm"
  MQ_HOST: "rabbit.cgm"
  # privacy consent connectivity
  CONSENT_HOST: "privacy-consent.cgm"
  CONSENT_PORT: "8080"
  CONSENT_ENDPOINT: "/api/int/consents/documents-access-verifications"
  # ehr connectivity
  EHRBASE_HOST: "http://ehrbase"
  HL7_HOST: "http://hl7parser"
  EHRBASE_PORT: "8080"
  HL7_PORT: "8088"
  EHR_PATH: "ehrbase/rest/openehr/v1/ehr/"
  HL7_PATH: "internal/api/openehr/composition/hl7"
  EHRBASE_USER: "myuser"
  EHRBASE_PASSWORD: "myPassword432"
