apiVersion: v1
kind: Service
metadata:
  name: repository
  labels:
    metrics: prometheus-repository-metrics
spec:
  selector:
    app: repository
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
