apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehrbase-db
spec:
  selector:
    matchLabels:
      app: ehrbase-db
  template:
    metadata:
      labels:
        app: ehrbase-db
    spec:
      imagePullSecrets:
        - name: nexus-image-pull
      containers:
        - name: ehrbase-db
          image: ehrbase-db
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ehrbase-db
            - secretRef:
                name: ehrbase-db
---
apiVersion: v1
kind: Service
metadata:
  name: ehrbase-db
spec:
  selector:
    app: ehrbase-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ehrbase-db
data:
  POSTGRES_USER: "postgres"
  EHRBASE_USER: "ehrbase"
  EHRBASE_USER_ADMIN: "ehrbaseadmin"
  TZ: "Europe/Warsaw"
