apiVersion: v1
kind: Service
metadata:
  name: atna
  labels:
    metrics: prometheus-atna-metrics
spec:
  selector:
    app: atna
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
