apiVersion: v1
kind: ConfigMap
metadata:
  name: adminer-cm
data:
  POSTGRES_DB: adminer_db
  SQL_ENGINE: django.db.backends.postgresql
  DATABASE_HOST: db
  DATABASE_PORT: "5432"
  VERIFY_CERT_API_PATH: api/v1/cert/verify
  # logging configuration
  DEBUG: "0"
  LOGLEVEL: "DEBUG"
