apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        auth: ws-security
    spec:
      imagePullSecrets:
        - name: nexus-image-pull
      containers:
        - name: registry
          image: registry
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: registry-cm
            - configMapRef:
                name: registry-cm-mpi
            - secretRef:
                name: registry-secret
            - secretRef:
                name: registry-secret-mpi
