apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: Opaque
data:
  DB_USER: cmVnaXN0cnlfZGJfdXNlcg==
  DB_PASS: cGFzc3dvcmQ=
  AUTH_TOKEN: RDNFRjUzNzExNDVBNDU2Nzk0RUUyNTRDRDcwMkJEOUM=
  MQ_PASS: ZWRt