apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: registry-metrics
spec:
  endpoints:
  - path: /prometheus/registry/metrics
    interval: 15s
    targetPort: 8080
  selector:
    matchLabels:
      metrics: prometheus-registry-metrics
