apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    metrics: prometheus-registry-metrics
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
