apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-bridge
  template:
    metadata:
      labels:
        app: fhir-bridge
    spec:
      containers:
        - name: fhir-bridge
          image: fhir-bridge
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: fhir-bridge
---
apiVersion: v1
kind: Service
metadata:
  name: fhir-bridge
spec:
  type: ClusterIP
  selector:
    app: fhir-bridge
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fhir-bridge
data:
  FHIR_BRIDGE_EHRBASE_BASE_URL: http://ehrbase.ives.svc.cluster.local:8080/ehrbase
  TZ: "Europe/Warsaw"