apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  namespace: ives

namespace: ives


configMapGenerator:
  - name: docker-entrypoint-initdb
    files:
      - resources/db/docker-entrypoint-initdb.d/01_repository_db_init.sql
      - resources/db/docker-entrypoint-initdb.d/02_registry_db_init.sql
      - resources/db/docker-entrypoint-initdb.d/03_encoder_db_init.sql
      - resources/db/docker-entrypoint-initdb.d/04_adminer_db_init.sql
      - resources/db/docker-entrypoint-initdb.d/05_atna_db_init.sql


resources:
  - resources/adminer/configmap.yaml
  - resources/adminer/deployment.yaml
  - resources/adminer/service.yaml
  - resources/adminer/netpol.yaml
  - resources/adminer/secret.yaml
  - resources/adminer/servicemonitor.yaml
  - resources/atna/configmap.yaml
  - resources/atna/deployment.yaml
  - resources/atna/service.yaml
  - resources/atna/secret.yaml
  - resources/atna/servicemonitor.yaml
  - resources/db/statefulset.yaml
  - resources/db/service.yaml
  - resources/db/secret.yaml
  - resources/encoder/configmap.yaml
  - resources/encoder/deployment.yaml
  - resources/encoder/service.yaml
  - resources/encoder/secret.yaml
  - resources/ingress/ingress.yaml
  - resources/registry/configmap-mpi.yaml
  - resources/registry/configmap.yaml
  - resources/registry/deployment.yaml
  - resources/registry/service.yaml
  - resources/registry/secret-mpi.yaml
  - resources/registry/secret.yaml
  - resources/registry/servicemonitor.yaml
  - resources/repository/configmap-mpi.yaml
  - resources/repository/configmap.yaml
  - resources/repository/deployment.yaml
  - resources/repository/service.yaml
  - resources/repository/secret-mpi.yaml
  - resources/repository/secret.yaml
  - resources/repository/servicemonitor.yaml
  - resources/signer/deployment.yaml
  - resources/signer/service.yaml
  - resources/ehr/ehrbase/
  - resources/ehr/ehrbase-db/
  - resources/ehr/ehrcontrol/
  - resources/ehr/fhir-bridge/
  - resources/ehr/hl7parser/

images:
  - name: adminer
    newName: nexus-external.loc.cgmpolska.pl:5010/adminer
    newTag: 1.3.8
  - name: atna
    newName: nexus-external.loc.cgmpolska.pl:5010/atna
    newTag: 1.2.3
  - name: encoder
    newName: nexus-external.loc.cgmpolska.pl:5010/encoder
    newTag: 2.12.14
  - name: registry
    newName: nexus-external.loc.cgmpolska.pl:5010/registry
    newTag: 1.35.59
  - name: repository
    newName: nexus-external.loc.cgmpolska.pl:5010/repository
    newTag: 1.30.45
  - name: signer
    newName: nexus-external.loc.cgmpolska.pl:5010/signer
    newTag: 1.0.0
  - name: ehrbase
    newName: ehrbase/ehrbase
    newTag: 0.27.4
  - name: ehrbase-db
    newName: nexus-external.loc.cgmpolska.pl:5010/ehrbase-db
    newTag: 1.1.1
  - name: ehrcontrol
    newName: ehrbase/ehrcontrol
    newTag: latest
  - name: fhir-bridge
    newName: ehrbase/fhir-bridge
    newTag: latest
  - name: hl7parser
    newName: nexus-external.loc.cgmpolska.pl:5010/hl7parser
    newTag: 1.1.13
